version: '3'
services:
    flask-server:
        container_name: flask_app
        build:
          context: ./flask/
          dockerfile: Dockerfile
        command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
        ports:
            - "5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        container_name: redis_db
        image: redis

    nginx:
        container_name: nginx_server
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        restart: always
        depends_on:
            - flask-server
            - redis
        ports:
            - 80:80
#
#        build:
#            context: ./nginx/
#            dockerfile: Dockerfile
#        restart: always
#        ports:
#            - 1337:80
#        depends_on:
#            - flask-server
#        links:
#            - flask-server